sudo: false
env:
  global:
    - DJANGO_DEBUG=True
    - DJANGO_SETTINGS_MODULE=tests.settings
  matrix:
    - DJANGO="django>=1.8,<1.9"
    - DJANGO="django>=1.9,<1.10"
    - DJANGO="django>=1.10,<1.11"
language: python
python:
  - '2.7'
install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install -e .[testing]
script:
  - make -C rql_filter/parser
  - flake8 . --exclude=parser.py,migrations
  - django-admin migrate
  - py.test
